# Generated by Django 3.2.8 on 2021-10-27 09:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsit_app', '0003_auto_20211026_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelposts',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='channelposts',
            name='post_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
